# Generated by Django 2.1.2 on 2018-10-15 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 7, 44, 32, 643113)),
        ),
    ]
