# Generated by Django 2.1.2 on 2018-10-15 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20181015_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 8, 33, 29, 582523)),
        ),
    ]
