# Generated by Django 2.1.2 on 2018-10-16 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20181015_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 1, 47, 35, 648342)),
        ),
    ]
